tezos-commons/baseDAO

docs/specification.md

Problem: After token related entrypoints are done, we should add other
entrypoints that is specified in the doc specification.
Solution: Add other entrypoints from the doc, add information about
"Creation Phase".
[Rendered](https://github.com/tqtezos/baseDAO/blob/rinn7e/%2310-non-token-entrypoint-spec/docs/specification.md)
Resolves #10 
- Tests
- Haddock

WIP: [#10] Add non-token entrypoints and BaseDAO configuration

---

app/Main.hs
nix/sources.json
scripts/test.bats
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Management.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
stack.yaml
stack.yaml.lock
test/Test/BaseDAO/FA2.hs
test/Test/Common.hs
test/Test/Management.hs

Implements code and tests for `transferOwnership`/`acceptOwnership` entrypoints.
Resolves #16 
- Tests
- Haddock

[#16] Implement transfer ownership entrypoints

---

nix/sources.json
src/Lorentz/Contracts/BaseDAO/FA2.hs
stack.yaml
stack.yaml.lock
test/Test/BaseDAO/FA2.hs

1. Update `morley-ledgers` to use current master, and also updates `Morley`, `Lorentz` dependencies as well.
2. Changes code/tests to use ADT types.
Resolves #23 
- Tests
- Haddock

[#23] Update dependencies and change code to use ADT

---

docs/specification.md
package.yaml
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/FA2.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
test/Test/BaseDAO/FA2.hs

This PR adds two FA2 Entrypoints - `balance_of` and `transfer`
Resolves #6
- Tests
- Haddock

Pru stephan/#6 implement fa2 functionality

---

docs/specification.md

New changes in the specification includes:
- Remove `Natural` param from `propose` entrypoint which determines how
many tokens needed for a vote.
- One vote now always requires one unfrozen token.
- `vote` entrypoint now accepts a list of votes which allows users to
vote on multiple proposals. Users now are allow to specify amount of votes
they want on a proposal as long as they have enough unfrozen tokens.
- Add extra fields in the configuration to set the maximum amount of
proposals, votes, and max/min value of quorum threshold and
voting_period.
- Add more custom errors needed for BaseDAO.
- Fix various small changes and improve readability of the
specification.
Thread for detail: 
- https://tocquevillegroup.slack.com/archives/C01BTEPMY5U/p1602081573007500
- …

Update specification according to the feedback

---

docs/specification.md
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/FA2.hs
src/Lorentz/Contracts/BaseDAO/Management.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
test/Test/BaseDAO/FA2.hs
test/Test/Management.hs

Updates the specification with the required changes.
Resolves #17 
- Tests
- Haddock

[#17] Implement migration entrypoint

---

docs/specification.md
src/Lorentz/Contracts/BaseDAO/FA2.hs
test/Test/BaseDAO/FA2.hs

Previously, none could transfer frozen token, but the latest spec stated that admin can. This PR adds this opportunity to transfer entrypoint
Resolves #26 
- Tests
- Haddock

#26 update transfer check

---

.buildkite/pipeline.yml
LICENSES/AGPL-3.0-or-later.txt
README.md
ci.nix
scripts/ci/upload-autodoc.sh

This PR adds documentation generation to CI using our standard approach. Now README refers to documentation file which is updated automatically on each push to `master`.
Resolves #18
- Tests
- Haddock

[#18] Create, upload and verify documentation on CI

---

app/Main.hs
docs/specification.md
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/FA2.hs
src/Lorentz/Contracts/BaseDAO/Management.hs
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
test/Test/BaseDAO/FA2.hs
test/Test/BaseDAO/Management.hs
test/Test/BaseDAO/Proposal.hs
test/Test/BaseDAO/ProposalConfig.hs
test/Test/Common.hs

Problem: After #5 and #6 we will have FA2 entrypoints, but there
are more in the specification. We are going to focus implementing
proposals and voting in this issue.
Solution: Add all entrypoints related to proposals and voting. Add
tests for these entrypoints.
Resolves #14 
- Tests
- Haddock

[#14] Implement proposals and voting logic with tests

---

.buildkite/pipeline.yml
docs/specification.md
package.yaml
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Management.hs
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Token.hs
src/Lorentz/Contracts/BaseDAO/Token/FA2.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
test/Test/BaseDAO/Management.hs
test/Test/BaseDAO/Proposal.hs
test/Test/BaseDAO/ProposalConfig.hs
test/Test/BaseDAO/Token.hs
test/Test/BaseDAO/Token/FA2.hs
test/Test/Common.hs

Problem: There are other token entrypoints that are missing:
`mint`, `burn`, `transfer_contract_tokens`, and `token_address`.
Solution: Implements all those missing entrypoints, and add tests for
them.
Resolves #15 
- Tests
- Haddock

[#15] Implement non-FA2 token functions

---

.buildkite/pipeline.yml
ci.nix
nix/sources.json
package.yaml
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Management.hs
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Token.hs
src/Lorentz/Contracts/BaseDAO/Token/FA2.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
stack.yaml
stack.yaml.lock
test/Test/BaseDAO/Limits.hs
test/Test/BaseDAO/ProposalConfig.hs

Applies optimizations to reduce contract size mentioned in #38.
This yet depends on [MR in Morley](https://gitlab.com/morley-framework/morley/-/merge_requests/651)
Resolves (partially) #38
- Tests
- Haddock
- Misc

[#38] Reduce contract size

---

test/Test/BaseDAO/Proposal.hs

Problem: When running test in real delphi network, the voting period
(20s) is too short, since each block may take up to 30s.
Solution: Update voting_period to 60s.
Resolves #
- Tests
- Haddock

Fix failing tests in delphi due to too short voting period

---

app/Main.hs
docs/specification.md
package.yaml
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Management.hs
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
test/Test/BaseDAO/Limits.hs
test/Test/BaseDAO/Management.hs
test/Test/Common.hs

Here I check that `specification.md` matches against our implementation, except for entrypoints behaviour and errors that should be easier to check when autodoc is implemented.
Resolves (partially) #29
- Tests
- Haddock

[#29] Update specification

---

app/Main.hs
docs/specification.md
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Management.hs
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Token.hs
src/Lorentz/Contracts/BaseDAO/Token/FA2.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
src/Lorentz/Contracts/GameDAO.hs
src/Lorentz/Contracts/TrivialDAO.hs
test/Test/BaseDAO/Doc.hs
test/Test/BaseDAO/Limits.hs
test/Test/BaseDAO/Management.hs
test/Test/BaseDAO/Proposal.hs
test/Test/BaseDAO/ProposalConfig.hs
test/Test/BaseDAO/Token.hs
test/Test/BaseDAO/Token/FA2.hs
test/Test/Common.hs
test/Test/GameDAO.hs

Here I add `contractExtra` type parameter to storage and config, and update the decision lambda respectively.
Resolves (partially) #29
- Tests
- Haddock

[#29] Improve decision lambda

---

.buildkite/pipeline.yml
test/Test/BaseDAO/Proposal.hs

Problem: We're now running tests on local-chain. However, we should
also do it on real test network.
Solution: Add scheduled run on delphinet.
TODO:
~* change target branch in https://buildkite.com/serokell/basedao/settings/schedules/826742f8-378d-4776-bc3d-cb5f5a09b8d1~
~* add a sane timeout for scheduled job~
Resolves #35 
- Tests
- Haddock

[#35] Add scheduled delphinet run

---

app/Main.hs
ci.nix
scripts/ci/upload-autodoc.sh
scripts/test.bats

This is continuation of `d67a1cac` commit where I failed to perform the
full update.
Resolves #29
- Tests
- Haddock

[#29] Generate autodoc for `TrivialDAO`

---

README.md

Last fix for usage instructions. Depends on #49 and #61.
Resolves (partially) #29
- Tests
- Haddock

[#29] Cleanup readme

---

README.md

Problem: we know that printing contract by default produces the contract
that is not a valid Michelson due to indentation issues. This contract
cannot be originated.
Solution: mention `--oneline` workaround for now, so that everyone can
actually try the contract.
- Tests
- Haddock

[#29] Mention working instructions in README

---

ci.nix

Removes unused CI configuration.
https://issues.serokell.io/issue/OPS-1128
- Tests
- Haddock

CI: clean up haskell.nix usage

---

baseDAO.cabal
docs/specification.md
nix/sources.json
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Doc.hs
src/Lorentz/Contracts/BaseDAO/Management.hs
src/Lorentz/Contracts/BaseDAO/Permit.hs
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Token/FA2.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
stack.yaml.lock
template/snapshot.yaml
template/templateDAO.cabal
test/Test/BaseDAO/Proposal.hs
test/Test/BaseDAO/Token.hs
test/Test/BaseDAO/Token/FA2.hs
test/Test/Common.hs
test/Test/GameDAO.hs

Add permit to `vote` entrypoint.
This depends on [changes in Morley](https://gitlab.com/morley-framework/morley/-/merge_requests/683).
Now in Michelson `vote` entrypoint argument looks like
```
(list %vote (pair :permit_protected (pair 
(bytes %proposal_key)
(pair 
(bool %vote_type)
(nat %vote_amount)))
(option %permit (pair 
(key %key)
(signature %signature))))))))
```
Resolves #56
- Tests
- Haddock

[#56] Permits in vote

---

docs/specification.md

Some last changes related to #29.
Resolves #29
- Tests
- Haddock

[#29] Final points

---

docs/registry.md
docs/treasury.md

Copy description of 2 DAOs from https://gist.github.com/gromakovsky/8fb38c6992bf779e68241a31630f39d5
Is needed for #73
- Tests
- Haddock

[#73] Add specifications for DAO contracts

---

.buildkite/pipeline.yml
scripts/ci/validate-cabal-files.sh

`diff` was not in the PATH and the error checking was improper, so the job was always passing
Relates #65
- Tests
- Haddock

[#65] Fix cabal file validation in CI

---

.buildkite/pipeline.yml
app/Main.hs
baseDAO.cabal
ci.nix
docs/specification.md
scripts/ci/upload-autodoc.sh
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
src/Lorentz/Contracts/GameDAO.hs
src/Lorentz/Contracts/RegistryDAO.hs
src/Lorentz/Contracts/RegistryDAO/Doc.hs
src/Lorentz/Contracts/RegistryDAO/Types.hs
template/app/Main.hs
test/Test/BaseDAO/ProposalConfig.hs
test/Test/Integrational/Common.hs
test/Test/Integrational/RegistryDAO.hs
test/Test/RegistryDAO.hs

Problem: We need to develop 2 DAO contracts: registry and treasury for
the new DAO frontend. We implement only RegistryDAO in this MR for now.
Solution: Add `RegistryDAO` according to specification, add tests.
Specification: https://gist.github.com/gromakovsky/8fb38c6992bf779e68241a31630f39d5
Resolves first part of #73
- Tests
- Haddock

[#73] Implement RegistryDAO

---

docs/specification.md
src/BaseDAO/CLI.hs
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Doc.hs
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Token.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
src/Lorentz/Contracts/GameDAO.hs
src/Lorentz/Contracts/RegistryDAO.hs
src/Lorentz/Contracts/TrivialDAO.hs
template/app/Main.hs
test/Test/BaseDAO/Limits.hs
test/Test/BaseDAO/Proposal.hs
test/Test/BaseDAO/ProposalConfig.hs
test/Test/Common.hs
test/Test/GameDAO.hs
test/Test/Integrational/Common.hs
test/Test/RegistryDAO.hs

Allow DAOs have custom entrypoints.
If this implementation is justified, I'll update the spec.
Resolves #86
- Tests
- Haddock

[#86] Add custom entrypoints

---

.buildkite/pipeline.yml
app/Main.hs
baseDAO.cabal
ci.nix
docs/specification.md
scripts/ci/upload-autodoc.sh
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Doc.hs
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Token.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
src/Lorentz/Contracts/TreasuryDAO.hs
src/Lorentz/Contracts/TreasuryDAO/Doc.hs
src/Lorentz/Contracts/TreasuryDAO/Types.hs
test/Test/BaseDAO/Management.hs
test/Test/BaseDAO/Proposal.hs
test/Test/BaseDAO/Token.hs
test/Test/Common.hs
test/Test/GameDAO.hs
test/Test/Integrational/RegistryDAO.hs
test/Test/RegistryDAO.hs
test/Test/TreasuryDAO.hs

Problem: We need to develop 2 DAO contracts: registry and treasury for
the new DAO frontend. We implement only RegistryDAO in this MR for now.
Solution: Add `TreasuryDAO` according to specification, add tests.
Resolves #73 
- Tests
- Haddock
Problem: We need to develop 2 DAO contracts: registry and treasury for
the new DAO frontend. We implement only RegistryDAO in this MR for now.
Solution: Add `RegistryDAO` according to specification, add tests.

[#73] Implement TreasuryDAO

---

README.md
baseDAO.cabal
cabal.project
docs/specification.md
package.yaml
scripts/test.bats
src/BaseDAO/CLI.hs
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/TZIP16Metadata.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
stack.yaml.lock
template/snapshot.yaml
test/Test/BaseDAO/Limits.hs
test/Test/BaseDAO/Management.hs
test/Test/Common.hs
test/Test/Integrational/Common.hs

Include metadata into our contract that refers to another contract, and provide means to fill baseDAO metadata in that other contract. 
Depends on a [PR in morley-metadata](https://gitlab.com/morley-framework/morley-metadata/-/merge_requests/6).
Resolves #80
- Tests
- Haddock

[#80] TZIP-16 metadata

---

baseDAO.cabal
ligo/src/management.mligo
ligo/src/token.mligo
ligo/src/token/fa2.mligo
ligo/test/Ligo/BaseDAO/Helper.hs
ligo/test/Ligo/BaseDAO/Types.hs
ligo/test/Test/Ligo/BaseDAO/Token/FA2.hs
ligo/test/baseDAO-ligo-tests.cabal
package.yaml
src/BaseDAO/ShareTest/Common.hs
src/BaseDAO/ShareTest/FA2.hs
src/Lorentz/Contracts/BaseDAO/Token/FA2.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
test/Test/BaseDAO/Management.hs
test/Test/BaseDAO/Token/FA2.hs

Problem: We need to implement LIGO version of BaseDAO contract. First of
all we should implement FA2 entrypoints and test it.
Solution: Implement FA2 entrypoints for LIGO version of BaseDAO and add
its tests.
Resolves #95 
- Tests
- Haddock

[#95] Implement FA2 endpoints for LIGO version

---

baseDAO.cabal
ligo/src/token.mligo
ligo/test/Test/Ligo/BaseDAO/Common.hs
ligo/test/Test/Ligo/BaseDAO/Token.hs
ligo/test/Test/Ligo/BaseDAO/Token/FA2.hs
ligo/test/baseDAO-ligo-tests.cabal
src/BaseDAO/ShareTest/Common.hs
src/BaseDAO/ShareTest/Token.hs

Problem: Token-related entrypoints for LIGO is not implemented yet.
Solution: Implemented token-related entrypoints for LIGO and add their
tests.
Resolves #102 
- Tests
- Haddock

[#102] Implement Token-related endpoints for LIGO version

---

docs/specification-ligo.md
docs/specification.md
ligo/src/base_DAO.mligo
ligo/src/common.mligo
ligo/src/management.mligo
ligo/src/token.mligo
ligo/src/token/fa2.mligo
ligo/src/types.mligo
ligo/test/Ligo/BaseDAO/Types.hs
ligo/test/Test/Ligo/BaseDAO/Management.hs
ligo/test/baseDAO-ligo-tests.cabal

1. Implements Management entrypoints for the LIGO contract along with test (mostly copied from tests for the Haskell version)
2. Refactor parameter to avoid multiple calls to `ensure_admin` and `ensure_not_migrated` functions.
3. Update specifications.
Resolves #100 and addresses #91
- Tests
- Haddock

[#100] Management LIGO entrypoints

---

.buildkite/pipeline.yml
ci.nix
ligo/test/Ligo/Util.hs
ligo/test/baseDAO-ligo-tests.cabal
ligo/test/package.yaml

This PR updates our CI to run tests for the LIGO contract.
Currently we run them only on emulator because the fail on network due to oversized operation. An issue about that will be created soon.
Resolves #57
- Tests
- Haddock

[#57] Add `ligo-test` in CI

---

README.md
docs/specification-ligo.md
ligo/README.md
ligo/test/README.md

Problem: The LIGO version of the contract only has some basic
documentation set up, we need to extend it.
Solution: Update LIGO README.md, test README.md, and link LIGO doc to
the main README instead of a PR.
Resolves #108 
- Tests
- Haddock

[#108] Improve LIGO version documentation

---

.buildkite/pipeline.yml
ci.nix
ligo/Makefile

Problem: 'morley' has an option for contract optimization, which is
supposed to reduce contract size and its gas consumption.
Solution: Use 'morley optimize' for the compiled ligo contract, thus
we can test and provide optimized version of baseDAO contract.
Resolves #119 
- Tests
- Haddock

[#119] Optimize compiled ligo contract

---

.buildkite/pipeline.yml

Avoid running `create auto prerelease` job on schedule
Relates #105
- Tests
- Haddock

[#105] Filter autoreleasing job

---

ligo/README.md
ligo/src/helper/unpack.mligo
ligo/src/treasuryDAO.mligo
ligo/src/treasuryDAO/types.mligo
src/Lorentz/Contracts/TreasuryDAO/Types.hs

Problem: As an example, we would like to implement Treasury DAO contract
using ligo version of the BaseDAO contract.
Solution: Implement configuration lambdas for BaseDAO contract which
implements Treasury DAO behavior.
Part of #117 
- Tests
- Haddock

[#117] Implement Treasury DAO using LIGO version 

---

ci.nix
ligo/Makefile
ligo/README.md
ligo/haskell/baseDAO-ligo-meta.cabal
ligo/haskell/package.yaml
ligo/haskell/src/Ligo/Util.hs
ligo/haskell/test/Test/Ligo/RegistryDAO.hs
ligo/src/registryDAO.mligo

1. Add the ligo-command to generate a BaseDAO storage with lambdas implementing the RegistryDAO pattern to the ligo Makefile
2. Implement tests to check registryDAO lambda behavior. Right now only `proposalCheck` and `rejectedProposalReturnValue` lambdas are tested.
Resolves #116 
- Tests
- Haddock

[#116] Add registryDAO tests

---

ci.nix
ligo/Makefile
ligo/README.md
ligo/haskell/baseDAO-ligo-meta.cabal
ligo/haskell/test/Test/Ligo/BaseDAO/Common.hs
ligo/haskell/test/Test/Ligo/BaseDAO/Proposal.hs
ligo/haskell/test/Test/Ligo/BaseDAO/Token.hs
ligo/haskell/test/Test/Ligo/BaseDAO/Token/FA2.hs
ligo/haskell/test/Test/Ligo/TreasuryDAO.hs
ligo/src/treasuryDAO.mligo
ligo/src/treasuryDAO/types.mligo
src/BaseDAO/ShareTest/Common.hs
src/Lorentz/Contracts/TreasuryDAO.hs
src/Lorentz/Contracts/TreasuryDAO/Types.hs
test/Test/Common.hs
test/Test/RegistryDAO.hs
test/Test/TreasuryDAO.hs

Problem: We have implemented Treasury DAO in LIGO, but we have not added
the tests for it yet.
Solution: Add tests for LIGO Treasury DAO.
Resolves #117  
- Tests
- Haddock

[#117] Add LIGO Treasury DAO tests

---

docs/registry.md
ligo/haskell/test/Test/Ligo/RegistryDAO.hs
ligo/src/registryDAO.mligo
ligo/src/registryDAO/types.mligo
src/Lorentz/Contracts/RegistryDAO.hs
src/Lorentz/Contracts/RegistryDAO/Types.hs
test/Test/RegistryDAO.hs

1. Adds custom entrypoint to lookup registry values to both LIGO and Lorentz versions of RegistryDAO contract. 
2. Adds tests for both and updates specification.
More detailed description are included in commit messages.
Resolves #113 
- Tests
- Haddock

[#113] RegistryDAO lookup-registry view

---

docs/specification-ligo.md
ligo/Makefile
ligo/haskell/src/Ligo/BaseDAO/Types.hs
ligo/haskell/test/Test/Ligo/BaseDAO/Proposal.hs
ligo/src/base_DAO.mligo
ligo/src/defaults.mligo
ligo/src/proposal.mligo
ligo/src/types.mligo
src/BaseDAO/ShareTest/Proposal/Flush.hs

It is desirable to prevent spam by setting a configurable fixed fee for submitting a proposal. We need to support both fees in Tezos and in the native asset.
PR checklist:
Resolves #67 
- Tests
- Haddock

[#67] Add a configurable fixed fee for a proposal

---

ligo/haskell/src/Ligo/BaseDAO/Types.hs
ligo/src/proposal.mligo
ligo/src/types.mligo
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Types.hs

Problem: We need to be able to figure out if some voter voted for or against a proposal.
Solution: For the relevant voters, change the `Natural` so that it's a right-combed `(Natural, VoteType)`, which allows us to determine more about the vote.
Resolves #151
- Tests
- Haddock

[#151] Store more info for RegistryDAO

---

Makefile
docs/specification.md
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/FA2.hs
haskell/test/Test/Ligo/BaseDAO/Management.hs
haskell/test/Test/Ligo/BaseDAO/Token/FA2.hs
src/base_DAO.mligo
src/defaults.mligo
src/management.mligo
src/types.mligo
typescript/baseDAO/src/api.ts
typescript/baseDAO/src/generated/Confirm_migration.ts
typescript/baseDAO/src/generated/Migrate.ts
typescript/baseDAO/src/generated/Parameter.ts
typescript/baseDAO/src/index.ts

Removing migration entrypoints, because in future all migrations will happen manually
Resolves #173 
- Tests
- Haddock

[#173] Remove migration functionality

---

Makefile
docs/building.md
src/defaults.mligo
src/registryDAO.mligo
src/registryDAO/types.mligo
src/treasuryDAO.mligo
src/treasuryDAO/types.mligo
src/types.mligo

We were asked to add some additional parameters to Makefile configuration for all our DAO's
Resolves #
- Tests
- Haddock

[#183] Add more options to Makefile

---

docs/registry.md
docs/specification.md
docs/treasury.md
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/Integrational/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Proposal.hs
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/common/types.mligo
src/registryDAO.mligo
src/registryDAO/types.mligo
src/treasuryDAO.mligo
src/treasuryDAO/types.mligo
src/types.mligo

Problem: The `proposal_metadata` is currently a `(string, bytes) map`,
however it is not the best representation due to unpacking issues.
Solution: Update `proposal_metadata` from `(string, bytes) map` to
`bytes`, make adjustment to all the tests.
Resolves #189
- Tests
- Haddock

[#189] Update `proposal_metadata` to `bytes`

---

.buildkite/pipeline.yml
Makefile
scripts/ci/validate-typescript-api.sh
typescript/baseDAO/src/api.ts
typescript/baseDAO/src/generated/Propose.ts
typescript/baseDAO/src/index.ts

Adds checks to ensure that the typescript files have been regenerated to match any change to contract interface.
Resolves #184 
- Tests
- Haddock

[#184] Typescript checks in CI 

---

Makefile
docs/building.md
docs/specification.md
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Ligo/BaseDAO/Contract.hs
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Bounds.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Config.hs
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/base_DAO.mligo
src/defaults.mligo
src/proposal.mligo
src/types.mligo
typescript/baseDAO/src/api.ts
typescript/baseDAO/src/generated/Parameter.ts
typescript/baseDAO/src/generated/Set_quorum_threshold.ts
typescript/baseDAO/src/index.ts

Remove the 'set_quorum_threshold' entrypoint and the associated code and the
max_quorum_threshold, min_quorum_threshold limits that are part of the
configuration in storage.
Resolves #213 
- Tests
- Haddock

[#213] Remove set_quorum_threshold and its limits from config

---

Makefile
docs/specification.md
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Config.hs
src/base_DAO.mligo
src/defaults.mligo
src/proposal.mligo
src/types.mligo
typescript/baseDAO/src/generated/Parameter.ts
typescript/baseDAO/src/generated/Set_fixed_fee_in_token.ts

Removes set_fixed_fee entrypoint and updates assocaited docs and tests.
Resolves #206 as well.
Resolves #211, #206
- Tests
- Haddock

[#211] Remove set_fixed_fee entrypoint

---

docs/specification.md
haskell/baseDAO-ligo-meta.cabal
haskell/package.yaml
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/Common/StorageHelper.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Config.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Proposal.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/base_DAO.mligo
src/permit.mligo
src/types.mligo
typescript/baseDAO/etc/basedao-sdk.api.md
typescript/baseDAO/src/api.ts
typescript/baseDAO/src/generated/Get_total_supply.ts
typescript/baseDAO/src/generated/Get_vote_permit_counter.ts
typescript/baseDAO/src/generated/Parameter.ts
typescript/baseDAO/src/index.ts

Problem: After #166, we no longer need `get_total_supply` and `get_vote_permit_counter`
entrypoints. We updated it to void instead of removing because the tests
need them to run properly. Currently, we found a way to check the
storage without using this entrypoints (By using `StorageView` instead)
so we should remove these entrypoints.
Solution: Remove `get_total_supply` and `get_vote_permit_counter`
entrypoints, add `FullStorageView`, update existing storage related type,
add `getTotalSupply` and `getVotePermitsCounter` storage check.
Resolves #214
- Tests
- Haddock

[#214] Remove `get_total_supply` and `get_vote_permit_counter`

---

docs/building.md
nix/sources.json
src/defaults.mligo
src/proposal.mligo
src/registryDAO.mligo
src/treasuryDAO.mligo

Bumps ligo version to the latest available and resolves warnings.
Part of #233
- Tests
- Haddock

[#233] bump Ligo

---

Makefile
docs/building.md
docs/specification.md
haskell/baseDAO-ligo-meta.cabal
haskell/package.yaml
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Integrational/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Config.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Vote.hs
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/defaults.mligo
src/proposal.mligo
src/proposal/freeze_history.mligo
src/proposal/quorum_threshold.mligo
src/token/fa2.mligo
src/types.mligo

This prepares for a new release by:
1. formalizing the concepts of `period`, `stage` and `cycle`
2. updating the spec other outdated  files
3. bumping the version number 
Part of #233
Note: despite this creating a new release I don't close the issues as more might come up to be done right away.
- Tests
- Haddock

[#233] clean up and prepare new release

---

haskell/src/Ligo/BaseDAO/TZIP16Metadata.hs
haskell/src/Ligo/BaseDAO/Types.hs
haskell/src/Ligo/Util.hs
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs

Problem: we have new issues for some TODOs that are not mentioned
in them as well as some old TODOs that no longer need attention.
Solution: remove outdated TODOs and update exising ones.
Part of #233
- Tests
- Haddock

[#233] update some TODOs and remove outdated ones

---

Makefile
docs/building.md
docs/specification.md
haskell/baseDAO-ligo-meta.cabal
haskell/package.yaml
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/Integrational/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Management.hs
haskell/test/Test/Ligo/BaseDAO/OffChainViews.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Vote.hs
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/defaults.mligo
src/proposal.mligo
src/proposal/quorum_threshold.mligo
src/types.mligo

Changes the time durations like voting period to be represented as a number of levels. Updates some configuration varaibles, documents and tests.
Resolves #237 
- Tests
- Haddock

[#237] Use levels instead of Timstamp for voting period duration

---

Makefile
docs/building.md
docs/specification.md
haskell/Makefile

Problem: Currently we suggest storing the contract's TZIP-16 metadata
on a separate on-chain contract, however it's getting more common to
store it on IPFS for many tokens.
Solution: Mention IPFS in the specification and readme.
Resolves #239 
- Tests
- Haddock

[#239] Suggest storing the contract metadata on IPFS

---

README.md
docs/building.md
docs/specification.md
haskell/baseDAO-ligo-meta.cabal
haskell/package.yaml
haskell/test/README.md

Problem: we want to make a new minor release to mark the last version
that uses a time-based logic.
Solution: bump release number and so some clean up on the docs.
Part of #233 
- Tests
- Haddock

[#233] clean up documentation and bump release number

---

docs/registry.md
docs/specification.md
docs/treasury.md
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Common/StorageHelper.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Config.hs
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/base_DAO.mligo
src/common/types.mligo
src/defaults.mligo
src/proposal.mligo
src/registryDAO.mligo
src/registryDAO/types.mligo
src/treasuryDAO.mligo
src/treasuryDAO/types.mligo
src/types.mligo

Apart from the implementation, I have refactored the arguments of the decision lambda a bit to make them records. This appeared to be required since the lambda had to return an optional guardian address after processing the proposal.
Resolves #287 
- Tests
- Haddock

[#287] Add proposal type to change guardian address

---

scripts/ci/validate-cabal-files.sh

We need to update our cabal files validation script to fix bug described here https://issues.serokell.io/issue/TM-560
Resolves TM-560
- Tests
- Haddock

[Chore] Fix bug with cabal validation

---

haskell/test/Test/Ligo/BaseDAO/Management/TransferOwnership.hs

Some checks in tests that currently uses additional contract calls were replaced with direct storage checks to reduce running time of tests.
Resolves #139
- Tests
- Haddock
- [  ] My commits comply with [the following policy](https://www.notion.so/serokell/Commit-and-PR-policy-4cf98e1a910a415d86b5f2491d9af1af).

[#139] Replace contract call checks with storage checks

---

.buildkite/pipeline.yml

Enable network (non-local chain) tests for ligo contract.
Resolves #124
- Tests
- Haddock

[#124] Enable non-local tests for ligo

---

.buildkite/pipeline.yml
nix/sources.json

Problem: Tezos has a new protocol and we should check if this project is
compatible with it.
Solution: Add local-chain and scheduled testnet jobs for the new
protocol to the CI configuration.
https://issues.serokell.io/issue/TM-595
- Tests
- Haddock

[Chore] Add hangzhou CI steps

---

Makefile
docs/building.md
haskell/app/Main.hs
haskell/baseDAO-ligo-meta.cabal
haskell/package.yaml
haskell/src/Ligo/BaseDAO/TZIP16Metadata.hs

Problem: There is a new TZIP-21 which is an extension of TZIP-16
that we should support.
Solution: Add support for TZIP-21.
Resolves #240
- Tests
- Haddock

[#240] Support TZIP-21 in the generated contract metadata

---

Makefile
docs/building.md
haskell/test/Test/Ligo/BaseDAO/Proposal/Config.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Vote.hs
src/variants/lambdaregistry/implementation.mligo
src/variants/lambdaregistry/types.mligo
src/variants/lambdatreasury/implementation.mligo
src/variants/lambdatreasury/types.mligo
src/variants/registry/implementation.mligo
src/variants/treasury/implementation.mligo

Problem: We missed to add storage building instructions for LambdaDAO
and variants to 'building.md'.
Solution: Add the instructions to 'building.md'.
Resolves #
- Tests
- Haddock

[#329] Add storage building instructions for LambdaDAO

---

docs/registry.md
docs/specification.md
docs/treasury.md
haskell/src/Ligo/BaseDAO/Common/Types.hs
haskell/test/SMT/Common/Helper.hs
haskell/test/SMT/Common/Run.hs
haskell/test/SMT/Model/BaseDAO/Token.hs
haskell/test/SMT/Model/BaseDAO/Types.hs
haskell/test/SMT/RegistryDAO.hs
haskell/test/SMT/TreasuryDAO.hs
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/Common.hs
haskell/test/Test/Ligo/RegistryDAO/Tests/Common.hs
haskell/test/Test/Ligo/RegistryDAO/Tests/FlushTransferProposal.hs
haskell/test/Test/Ligo/RegistryDAO/Tests/UpdateDelegate.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/common/types.mligo
src/variants/lambdaregistry/storage.mligo
src/variants/lambdatreasury/storage.mligo
src/variants/registry/implementation.mligo
src/variants/treasury/implementation.mligo
stack.yaml.lock

Problem: We need to support FA1.2 transfers in the transfer proposals.
Solution: Add a new branch to the transfer type to represent FA1.2 transfers. Implement handlers for this branch. Update tests to test FA1.2 transfer proposals.
Resolves #343
- Tests
- Haddock

[#343] Add ability to call FA1.2 transfers in proposals
