tezos-commons/baseDAO

docs/specification.md

Problem: in order to implement this smart contract we have to specify
its interface and logic.
Solution: add `docs/specification.md` with specification of the
required smart contract.
Currently only token entrypoints are described.
[Rendered](https://github.com/tqtezos/baseDAO/blob/gromak/specification/docs/specification.md)

Add token specification

---

.buildkite/pipeline.yml
ci.nix
nix/sources.json
package.yaml
stack.yaml
stack.yaml.lock
test/Test/BaseDAO/FA2.hs
test/Test/BaseDAO/Management.hs
test/Test/BaseDAO/Proposal.hs

Problem: we want to use a newer version of the `cleveland` package
because it has `tasty` integration and some new functionality
that we intend to use in tests.
We also want to run network tests on CI.
Solution: update versions of packages from Morley framework.
Tests have been updated to use new functions from `Morley.Nettest.Tasty`
instead of functions like `nettestTestExpectation` that are no longer
available.
Now CI runs network tests as well. In this PR it runs them only in local chain, but we'll add running in Delphinet as well (not in this PR).
Relevant upstream MR: https://gitlab.com/morley-framework/morley/-/merge_requests/613
Resolves #32
- Tests
- …

[#32] Update `cleveland`, run network tests on CI

---

package.yaml
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
test/Test/BaseDAO/Proposal.hs

Problem: Previously, it is not possible to do a `wait 3 seconds` in `Nettest`.
We need this to actually check if a voting period of a proposal is over or not.
Solution: Use `advanceTime` to properly test `flush` entrypoint. Remove
the workaround.
Resolves #30 
- Tests
- Haddock

[#30] Use `advanceTime` from `Nettest` to properly test `flush` entrypoint 

---

.stylish-haskell.yaml

Problem: this repository lacks `stylish-haskell` config.
Solution: add the one from Serokell's style guide. It seems to quite
match the formatting used in this project.
I'm not formatting existing files in order to avoid unnecessary
conflicts, things should get formatted over time anyway (assuming that
developers have autoformatting on save).
- Tests
- Haddock

Add stylish-haskell config

---

app/Main.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
src/Lorentz/Contracts/GameDAO.hs
test/Test/BaseDAO/Proposal.hs
test/Test/BaseDAO/Token.hs
test/Test/BaseDAO/Token/FA2.hs
test/Test/Common.hs
test/Test/GameDAO.hs

Problem: Our `baseDAO` executable can print one simple DAO contract.
This contract is parameterized with `defaultConfig` which is the
simplest possible config. It doesn't check anything about proposals,
its decision lambda does nothing, it doesn't slash returned amount.
I think we need to provide a better example that could be practically useful.
The initial document we received contains 4 DAOs: Registry DAO, BakerDAO,
DEXDAO, GameDAO. We can implement one of them or come up with something else (inspired by these 4).
Solution: Use `GameDAO` from the google doc specification as example.
Add proper `proposalMetadata`, `proposalCheck`, and
`rejectedProposalValue` that makes sense for `GameDAO`.
Resolves #36 
- Tests
[//]: # (Add more docs here if you have them in …

[#36] Add `GameDAO` contract as an example of `BaseDAO`

---

package.yaml
test/Test/Common.hs

Problem: due to hitting operation size limit we initialized empty
contract and then added there desired balance distribution and
operators, but that looks like extra work.
Solution: uncomment the old code that creates initial storage with all
the necessary balances and operators, remove contract calls that filled
them.
Related to #38.
- Tests
- Haddock

[#38] Instantiate contract immediately in tests

---

stack.yaml
stack.yaml.lock

Problem: our tests are quite slow, but recently one speed-up was
merged to cleveland, see
https://gitlab.com/morley-framework/morley/-/merge_requests/631
We would like to use it here to potentially speed-up existing tests.
Solution: update git commit of the `morley` repo.
None
- Tests
- Haddock

Update cleveland and morley-client revision

---

.buildkite/pipeline.yml
README.md
ci.nix
scripts/ci/upload-autodoc.sh

Problem: we recently added `GameDAO` contract with its own
documentation.
However, this documentation is not generated and checked by our CI,
it's hard to access it.
Solution: generate, check and upload it as part of CI, the same way
as we do for `BaseDAO`.
#29
- Tests
- Haddock

[#29] Build and upload GameDAO documentation on CI

---

src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Token.hs
src/Lorentz/Contracts/BaseDAO/Token/FA2.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
test/Test/BaseDAO/ProposalConfig.hs

Extract `unfreezeProposerTokens` since it is used 3 times and costs ~1300 bytes in overall.
**TODO:** this depends on an [MR in Morley](https://gitlab.com/morley-framework/morley/-/merge_requests/679), I'll measure the contract size once everything works.
Resolves (partially) #38
- Tests
- Haddock

[#38] Optimize `flush` slightly

---

docs/specification.md
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Doc.hs
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
test/Test/BaseDAO/Proposal.hs
test/Test/GameDAO.hs

Problem: When calling `flush`, `decisionLambda` or `rejectedValue` lambda may fail due to unexpected error. We should have a way to drop some proposals and a way to not flush proposals all at one.
Solution: 
- Refactor `sProposalKeyListSortByDate` to be a map with `(Timestamp, ProposalKey proposalMetadata)` as the key, and `()` as the value (Since value here is not important).
- Add `dropProposals` entrypoint
- Update `flush` entrypoint to accept a (Maybe Natural)
- Add tests for these new features
Resolves #69
- Tests
- Haddock

[#69] Allow `flush` to accepts an amout of proposals, add `dropProposals` entrypoint

---

test/Test/RegistryDAO.hs

Problem: `validConfigProposal` test in RegistyDAO contains
time-sensitive operations (`flush`). This currently does not work well
in delphinet tests.
Solution: Only run the test in emulator for now.
Resolves #
- Tests
- Haddock

Fix RegistryDAO tests failling during scheduled delphinet tests

---

test/Test/BaseDAO/Proposal.hs
test/Test/BaseDAO/ProposalConfig.hs
test/Test/Common.hs

Problem: The recent change makes the default storage having short voting
period. This results in a few tests failing due to time sensitive operation.
Solution: Set a longer voting period for those tests.
None
- Tests
- Haddock

Fix delphinet failing due to short voting period

---

src/Lorentz/Contracts/BaseDAO/Types.hs

This removes the redundant `:metadata` type annotation from the TZIP-16 metadata big_map.
Note: this resolves the issue because the `s` prefix problem has already been handled by 23189df87e4aa02d15b0bf3e727d452622a8c93d
Resolves #97
- Tests
- Haddock

[#97] Remove metadata type annotation

---

docs/specification-ligo.md
ligo/src/base_DAO.mligo
ligo/src/common.mligo
ligo/src/management.mligo
ligo/src/token.mligo
ligo/src/token/fa2.mligo
ligo/test/Test/Ligo/BaseDAO/Management.hs
ligo/test/Test/Ligo/BaseDAO/Token.hs
ligo/test/Test/Ligo/BaseDAO/Token/FA2.hs
src/BaseDAO/ShareTest/FA2.hs
src/BaseDAO/ShareTest/Token.hs
test/Test/BaseDAO/Token.hs
test/Test/BaseDAO/Token/FA2.hs

Problem: Current LIGO only fails with type `string` which is different
from the Lorentz version. Because of this, we require a `isLorentz`
check in the tests to be able to share the tests properly. We can update
the `failwith` in LIGO to be the same as lorentz which would make the
check no longer necessary.
Solution: Update LIGO `failwith` to be the same as Lorentz version,
remove `isLorentz` check in share tests.
Resolves #106  
- Tests
- Haddock

[#106] Update LIGO `failwith` to be the same as Lorentz version

---

ligo/README.md
ligo/src/defaults.mligo
ligo/src/proposal.mligo
ligo/src/registryDAO.mligo
ligo/src/registryDAO/types.mligo

Problem: As an example, we would like to implement RegistryDAO contract
using ligo version of the BaseDAO contract.
Solution: Implement configuration lambdas for BaseDAO contract which
implements RegistryDAO behavior.
Originally, RegistryDAO contract requires a parameterized contract, but
since it is not clear how to do this in LIGO, the Key/Value types are
just included as a type alias in the source file.
Apart from this, the implementation of decision lambda is a bit hackish
where the two types of proposals are distinguished by looking at the
included keys in the proposal metadata, which is just a `(string, bytes)
map`.
A dummy entrypoint is left in the RegistryDAO source file to facilitate
creation of a Michelson storage expression using the LIGO
compile_storage command.
During …

[#116] LIGO RegistryDAO contract using BaseDAO

---

docs/specification.md
src/Lorentz/Contracts/BaseDAO/Types.hs

Problem: Currently, `daoName` and `daoDescription` are  used only
for documentation and are not part of `Storage`. We should make it more
clear about that.
Solution: Make it clearer that these values are used only for documentation,
and not part of `Storage`.
Resolves #72 
- Tests
- Haddock

[#72] Cleanup Config

---

baseDAO.cabal
ligo/haskell/test/Test/Ligo/BaseDAO/Management.hs
src/BaseDAO/ShareTest/Common.hs
src/BaseDAO/ShareTest/FA2.hs
src/BaseDAO/ShareTest/Management.hs
test/Test/BaseDAO/Management.hs
test/Test/Common.hs

Problem: Management tests between Lorentz and LIGO version are very
similar. We should create shared tests to use between them instead to
reduce duplication.
Solution: Make management tests shared between Lorentz and LIGO.
Resolves #129 
- Tests
- Haddock

[#129] Make management entrypoint tests shared

---

.buildkite/pipeline.yml
ci.nix
docs/specification-ligo.md
ligo/Makefile
ligo/README.md
ligo/haskell/baseDAO-ligo-meta.cabal
ligo/haskell/package.yaml
ligo/haskell/src/Ligo/BaseDAO/Types.hs
ligo/haskell/src/Ligo/Util.hs
ligo/haskell/test/Ligo/BaseDAO/Contract.hs
ligo/haskell/test/Test/Ligo/BaseDAO/Common.hs
ligo/haskell/test/Test/Ligo/BaseDAO/Management.hs
ligo/haskell/test/Test/Ligo/BaseDAO/Proposal.hs
ligo/haskell/test/Test/Ligo/BaseDAO/Token.hs
ligo/haskell/test/Test/Ligo/BaseDAO/Token/FA2.hs
ligo/haskell/test/Test/Ligo/RegistryDAO.hs
ligo/haskell/test/Test/Ligo/TreasuryDAO.hs
ligo/src/base_DAO.mligo
ligo/src/defaults.mligo
ligo/src/management.mligo
ligo/src/permit.mligo
ligo/src/proposal.mligo
ligo/src/registryDAO.mligo
ligo/src/startup.mligo
ligo/src/token.mligo
ligo/src/token/fa2.mligo
ligo/src/treasuryDAO.mligo
ligo/src/types.mligo

The first two commits of this PR are an attempt to reduce the cost without being to aggressive.
The refactoring that resulted from them (mostly the fist) has been quite successful, but it's still not nearly enough to fit into the limits.
The commit that follows (still a WIP because of missing tests and docs update) solves the origination problem by moving the entrypoint code from the `code` section to lambdas stored in the `storage` and provides a way to generate the parameter needed to load these lambdas into an originated contract
Resolves #123
- Tests
- Haddock

[#123] Reduce origination size and provide a simple guide for it

---

docs/specification-ligo.md
docs/specification.md
ligo/Makefile
ligo/haskell/src/Ligo/BaseDAO/Types.hs
ligo/haskell/test/Test/Ligo/BaseDAO/Common.hs
ligo/haskell/test/Test/Ligo/BaseDAO/OffChainViews.hs
ligo/haskell/test/Test/Ligo/BaseDAO/Token.hs
ligo/haskell/test/Test/Ligo/RegistryDAO.hs
ligo/src/base_DAO.mligo
ligo/src/defaults.mligo
ligo/src/permit.mligo
ligo/src/proposal.mligo
ligo/src/startup.mligo
ligo/src/token.mligo
ligo/src/token/fa2.mligo
ligo/src/types.mligo
src/BaseDAO/ShareTest/Common.hs
src/BaseDAO/ShareTest/OffChainViews.hs
src/BaseDAO/ShareTest/Proposal/Flush.hs
src/BaseDAO/ShareTest/Proposal/Proposal.hs
src/BaseDAO/ShareTest/Token.hs
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Doc.hs
src/Lorentz/Contracts/BaseDAO/TZIP16Metadata.hs
src/Lorentz/Contracts/BaseDAO/Token/FA2.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
test/Test/BaseDAO/OffChainViews.hs
test/Test/BaseDAO/Token.hs
test/Test/Common.hs
test/Test/Integrational/Common.hs

Problem: TZIP-12 specs say that `total_supply` SHOULD be provided but we
do not track total supply yet.
Solution: Track total supply for all the tokens, add off-chain and
on-chain `total_supply` view, and add tests to cover all the cases.
Resolves #126 
- Tests
- Haddock

[#126] Implement `total_supply` off-chain view

---

docs/registry.md
ligo/src/registryDAO.mligo
ligo/src/registryDAO/types.mligo
src/BaseDAO/CLI.hs
src/Lorentz/Contracts/BaseDAO/TZIP16Metadata.hs
src/Lorentz/Contracts/RegistryDAO.hs
src/Lorentz/Contracts/RegistryDAO/Types.hs
test/Test/RegistryDAO.hs

1. Adds a new proposal types to add/remove from the list of contract addressed stored in the contractExtra field. 
2. Adds a new field to registryDAO's extra data.
3. Refactor some LIGO code that decides on the proposal type.
4. Partially add the TZIP-16 storage view to fetch the stored list of contract addresses.
I got in a bit of a mess, and went in circles for a bit, trying to find a way to include the storage view in the Lorentz version of RegistryDAO contract. The issue is that the contract metadata appear to be exposed to the external world during the printing metadata command of the CLI app only. But right now this only prints the main metadata, and does not print metadata for the derived contracts. 
So right now,  I have just left the metadata for registryDAO with the TZIP-16 …

[#137] RegistryDAO  proposal type to maintain proposal receiver contract addresses

---

docs/registry.md
docs/treasury.md
ligo/Makefile
ligo/README.md
ligo/haskell/test/Test/Ligo/RegistryDAO.hs
ligo/haskell/test/Test/Ligo/TreasuryDAO.hs
ligo/src/registryDAO.mligo
ligo/src/treasuryDAO.mligo
ligo/src/treasuryDAO/types.mligo
src/Lorentz/Contracts/RegistryDAO/Types.hs
src/Lorentz/Contracts/TreasuryDAO/Types.hs
test/Test/RegistryDAO.hs

Problem: Currently, ligo uses unintuitive names like `a`, `b`, `c`, `d`,
`s_max`, `y` and `z`, which is not very good for the user.
Solution: Rename each of these with `frozen_scale_value`,
`frozen_extra_value`, `slash_scale_value`, `slash_division_value`,
`max_proposal_size`, `min_xtz_amount`, `max_xtz_amount`, respectively.
These changes were done in a few variable names, Makefile, docs etc and
old references to the short names were erased.
Resolves #155
- Tests
- Haddock

[#155] Use better names for ligo Makefile arguments

---

.buildkite/pipeline.yml
baseDAO.cabal
cabal.project
ci.nix
ligo/haskell/baseDAO-ligo-meta.cabal
nix/sources.json
nix/sources.nix
snapshot-stack2cabal.yaml

Updates dependencies used by CI to keep them up to date
Related issue: https://issues.serokell.io/issue/OPS-1174

CI: bump dependencies

---

ligo/haskell/test/Test/Ligo/RegistryDAO.hs
ligo/haskell/test/Test/Ligo/TreasuryDAO.hs
ligo/src/base_DAO.mligo
ligo/src/common.mligo
ligo/src/management.mligo
ligo/src/proposal.mligo
ligo/src/token.mligo
ligo/src/token/fa2.mligo
ligo/src/treasuryDAO.mligo
src/BaseDAO/ShareTest/FA2.hs
src/BaseDAO/ShareTest/Management.hs
src/BaseDAO/ShareTest/Proposal/Bounds.hs
src/BaseDAO/ShareTest/Proposal/Flush.hs
src/BaseDAO/ShareTest/Proposal/Proposal.hs
src/BaseDAO/ShareTest/Proposal/Vote.hs
src/BaseDAO/ShareTest/Token.hs
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Management.hs
src/Lorentz/Contracts/BaseDAO/Permit.hs
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/Token.hs
src/Lorentz/Contracts/BaseDAO/Token/FA2.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
src/Lorentz/Contracts/GameDAO.hs
src/Lorentz/Contracts/TreasuryDAO.hs
src/Lorentz/Contracts/TreasuryDAO/Types.hs
test/Test/GameDAO.hs
test/Test/RegistryDAO.hs
test/Test/TreasuryDAO.hs

Problem: In many places we fail with `Pair "string" Unit`, due to the
requirement in older Lorentz version. With the new Lorentz version, we
can fail with a normal string now.
Solution: Bump to latest Lorentz version to be able to use `NoErrorArg`, 
update LIGO code to fail with a normal string where possible. 
Resolves #131 
Depends on #144 
- Tests
- Haddock

[#131] Use `NoErrorArg` and remove `FAILWITH` `Pair "string" Unit` from LIGO

---

ligo/Makefile
ligo/README.md
ligo/haskell/src/Ligo/BaseDAO/Types.hs
ligo/src/defaults.mligo
ligo/src/registryDAO.mligo
ligo/src/treasuryDAO.mligo
ligo/src/types.mligo

Problem: We currently can't specify any parameters for metadata when
creating a contract with LIGO.
Solution: Have the `default_{registry,treasury}_DAO_full_storage`
functions accept a `(string, bytes) big_map` corresponding to the
metadata. In the Makefile, add `metadata_map` fields which the user can
specify.
Resolves #152
- Tests
- Haddock

[#152] Allow specifying a TZIP-16 metadata contract in the LIGO version

---

ligo/haskell/src/Ligo/BaseDAO/Types.hs
ligo/src/defaults.mligo
ligo/src/proposal.mligo
ligo/src/token/fa2.mligo
ligo/src/types.mligo
src/Lorentz/Contracts/BaseDAO/Proposal.hs
src/Lorentz/Contracts/BaseDAO/TZIP16Metadata.hs
src/Lorentz/Contracts/BaseDAO/Token/FA2.hs
src/Lorentz/Contracts/BaseDAO/Types.hs

This PR moves constants inlined in the code to the storage. Particularly, `unfrozen_token_id` and `frozen_token_id` were moved to the storage in both the Ligo and Lorentz versions. In the Lorentz version, the `Config` type has its fields inlined in various parts at the `Proposal` module, and it also has been moved to the storage and its usages properly updated.
Resolves #138
- Tests
- Haddock

[#138] Move all inlined constants to storage

---

baseDAO.cabal
docs/registry.md
ligo/Makefile
ligo/README.md
ligo/haskell/test/Test/Ligo/RegistryDAO.hs
ligo/haskell/test/Test/Ligo/TreasuryDAO.hs
ligo/src/common/types.mligo
ligo/src/registryDAO.mligo
ligo/src/registryDAO/types.mligo
ligo/src/treasuryDAO.mligo
ligo/src/treasuryDAO/types.mligo
src/Lorentz/Contracts/BaseDAO/Common/Types.hs
src/Lorentz/Contracts/TreasuryDAO.hs
src/Lorentz/Contracts/TreasuryDAO/Types.hs
test/Test/TreasuryDAO.hs

Problem: As in treasuryDAO, we should enable registryDAO to allow
transferring resources from a treasury.
Solution: Move some treasuryDAO types to ordinary types module. Add a
`Transfer_proposal` type to registryDAO and copy/paste some code from
treasuryDAO. Write two tests checking it works as intended.
Resolves #66
- Tests
- Haddock

[#66] Batch Transfer as a Proposal Type

---

cabal.project
docs/specification-ligo.md
docs/specification.md
ligo/haskell/src/Ligo/BaseDAO/Types.hs
ligo/haskell/test/Test/Ligo/BaseDAO/Proposal.hs
ligo/src/base_DAO.mligo
ligo/src/permit.mligo
ligo/src/types.mligo
src/BaseDAO/ShareTest/Proposal/Proposal.hs
src/BaseDAO/ShareTest/Token.hs
src/Lorentz/Contracts/BaseDAO.hs
src/Lorentz/Contracts/BaseDAO/Types.hs
stack.yaml.lock
template/snapshot.yaml

**Problem:** We need to somehow get data from storage but using views is insecure: other contracts can trick DAO into sending operations to arbitrary contracts.
**Solution:** Replace views with `void` entrypoints.
Resolves #166 
- Tests
- Haddock

[#166] Replace nat views with void entrypoints

---

cabal.project
src/Lorentz/Contracts/BaseDAO/TZIP16Metadata.hs
src/Lorentz/Contracts/RegistryDAO.hs
stack.yaml.lock
template/snapshot.yaml

`compileViewCode_` function was removed. Its usages were replaced by `unsafeCompileViewCode` from `morley-metadata`
Resolves #178 
- Tests
- Haddock

[#178] Use unsafe way to compile view code from morley-metadata

---

docs/specification.md
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Integrational/Management.hs
haskell/test/Test/Ligo/BaseDAO/Integrational/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Bounds.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Config.hs
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/defaults.mligo
src/proposal.mligo
src/types.mligo
typescript/baseDAO/src/api.ts
typescript/baseDAO/src/generated/Set_quorum_threshold.ts

Modifies the quorum threshold, as well as its settings, to be a fraction of the total supply of frozen tokens (instead of a fixed value).
Resolves #175
- Tests
- Haddock

[#175] make the quorum a fraction of Total Supply

---

docs/specification.md
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/Integrational/Management.hs
haskell/test/Test/Ligo/BaseDAO/Integrational/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Management.hs
haskell/test/Test/Ligo/BaseDAO/OffChainViews.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Token.hs
haskell/test/Test/Ligo/BaseDAO/Token/FA2.hs
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/common/types.mligo
src/defaults.mligo
src/helper/unpack.mligo
src/registryDAO.mligo
src/registryDAO/types.mligo
src/treasuryDAO.mligo
src/types.mligo

Problem: The `extra` field of the storage is a `contract_extra`,
which is currently defined as a `(string, bytes) map`.
This however poses a limitation, as `map` is strict and so the cost
in case of many key is too high.
Solution: Make `contract_extra` as `big_map` instead of map, update
various unpack related functions.
Resolves #188 
- Tests
- Haddock

[#188] Store `contract_extra` as a `big_map`

---

Makefile
docs/building.md
docs/specification.md
haskell/app/Main.hs
haskell/src/Ligo/BaseDAO/TZIP16Metadata.hs
haskell/src/Ligo/BaseDAO/Types.hs

In the PR that implements BYO extension, we added Makefile
arguments `governance_token_address` and `governance_token_id`. But the
build instructions was not updated to reflect this. This PR updates
`docs/building.md` file to include the new arguments in
`make` command samples. In addition the default token address was
changed to an address of the form `KT*` instead of `tz*`, to better
reflect the fact that it is an address of a smart contract. 
Resolves #170
- Tests
- Haddock

[#170] Update build instructions to include governance_token

---

.buildkite/pipeline.yml

Problem: If multiple nettests are running at the same time using same
data directory, a race condition may appear and thus CI jobs may fail.
Solution: Use unique data dir for each nettest run.
Relates #124
- Tests
- Haddock

[#124] Use new data dir for each nettest run

---

Makefile

We recently changed the `Makefile` storage targets to contain the arguments inside double quotes instead of single ones.
This however causes previously valid calls containing double quotes in the `metadata_map` and `ledger` options to fail for lack of escaping.
Solution: add automatic escaping to the `metadata_map` and `ledger` options.
None
- Tests
- Haddock

Add escaping to metadata_map and ledger Makefile option

---

docs/specification.md
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/Integrational/Management.hs
haskell/test/Test/Ligo/BaseDAO/Integrational/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Management.hs
haskell/test/Test/Ligo/BaseDAO/OffChainViews.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Token.hs
haskell/test/Test/Ligo/BaseDAO/Token/Common.hs
src/defaults.mligo
src/registryDAO.mligo
src/treasuryDAO.mligo
src/types.mligo

Problem: The `custom_entrypoints` is currently defined as a `(string, bytes) map`.
This however poses a limitation, as `map` is strict and so the cost
in case of many key is too high.
Solution: Make `custom_entrypoints` as `big_map` instead of map, make
`DynamicRec` using `BigMap` instead, remove `DynamicRecBigMap`.
Resolves #192 
- Tests
- Haddock

[#192] Change the `custom_entrypoints` type to `big_map`

---

haskell/src/Ligo/BaseDAO/TZIP16Metadata.hs
haskell/test/Test/Ligo/BaseDAO/OffChainViews.hs

Problem: We used to have a `token_address` entrypoint, but we removed
it in #85 because it's not very useful. We can instead make it an
off-chain view (according to TZIP-16).
Solution: Add off-chain view `token_address`, rename it to
`governance_token` view instead, add tests to cover this
view.
Resolves #92 
- Tests
- Haddock

[#92] Add `governance_token` off-chain view

---

docs/specification.md
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Token.hs
src/base_DAO.mligo
src/token.mligo
src/types.mligo
typescript/baseDAO/README.md
typescript/baseDAO/etc/basedao-sdk.api.md
typescript/baseDAO/src/api.ts
typescript/baseDAO/src/generated/Mint.ts
typescript/baseDAO/src/generated/Parameter.ts
typescript/baseDAO/src/index.ts

Problem: `mint` is an admin-only entrypoint that allow
generating tokens. This was intended to
be used mainly to set up the contract and then to not be used again.
However, it is possible to setup the ledger with correct initial value
at origination and we no longer need this entrypoint.
Solution: Remove `mint` entrypoint and remove all related
tests.
Resolves #208
- Tests
- Haddock

[#208] Remove the `mint` entrypoint 

---

Makefile
docs/building.md
docs/specification.md
haskell/test/Test/Ligo/RegistryDAO.hs
src/defaults.mligo
src/proposal.mligo
src/types.mligo

Problem: In the `Makefile` we have a default voting period of `11n`,
since this value is in seconds, this is too low for a realistic use.
Solution: Update voting period in Makefile to 950400 seconds (11 days).
Resolves #205 
- Tests
- Haddock

[#205] Update voting period in the Makefile from 11 seconds to 11 days

---

haskell/src/Ligo/BaseDAO/TZIP16Metadata.hs
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/OffChainViews.hs
haskell/test/Test/Ligo/BaseDAO/Token/Common.hs
haskell/test/Test/Ligo/BaseDAO/Token/Transfer.hs
haskell/test/Test/Ligo/BaseDAO/Token/UpdateOperators.hs
src/token/fa2.mligo
src/types.mligo

As per FA2, operators should be tracked for each `token_id`
This PR adds it to the stored operators and fixed the check accordingly.
Resolves #203
- Tests
- Haddock

[#203] single token operator

---

docs/specification.md
haskell/test/Test/Ligo/BaseDAO/Token/Transfer.hs
src/token/fa2.mligo

Problem: The `transfer` entrypoint has a special permission that
allows the `admin` (and only him) to transfer frozen tokens on the ledger.
This was intended as a shorthand for `mint` and `burn`, which granted him
the same ability. owever, since these have been removed (see #208 and #209) we should
remove this permission as well.
Solution: Remove the special permission which allow `admin` to transfer
frozen token.
Resolves #210 
- Tests
- Haddock

[#210] Remove the special `admin` permissions on `transfer`

---

docs/specification.md
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/Integrational/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Vote.hs
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/proposal.mligo

Problem: there is a discrepancy between the specifiction and the
implementation (and tests) for the cycles: in the spec we say that
proposals stages are only odd and voting ones even, but the contract
behaves in the opposite way.
Solution: it seems to be more sensible to follow the specification,
although the current implementation is just as valid of an option, so
the contract code and tests are updated.
Additionally, tests have been commented more to show this more clearly.
None
- Tests
- Haddock

Fix stages cycle to match the specification

---

Makefile
docs/building.md

Problem: In the storage generation section of Makefile we use
'Tezos.now' to fetch the current timestamp. But it appears that the
'ligo compile' command is not able to fetch the current timestamp
properly.
Solution: Use the 'date' command from environment to fetch the unix
timestamp and use it as a timestamp during storage generation.
Resolves #230 
- Tests
- Haddock

[#230] Fix Makefile to use proper current timestamp

---

.buildkite/pipeline.yml

Problem: In CI we have an auto prerelease step that creates a
prerelease based on master. Currently this only includes the
`baseDAO.tz` contract itself.
However, we can modify it to:
- compile all storage(s) with the default values
- generate the known metadata (for the ligo version only)
Solution: Add all trivialDAO, treasuryDAO, and registryDAO storages,
and add `known_metadata.json` to the pre-release step as assets.
Resolves #198
- Tests
- Haddock

[#198] Add more assets to the auto prerelease step

---

Makefile
docs/building.md
docs/specification.md
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/Integrational/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Config.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Vote.hs
haskell/test/Test/Ligo/BaseDAO/Token.hs
haskell/test/Test/Ligo/BaseDAO/Token/BalanceOf.hs
haskell/test/Test/Ligo/BaseDAO/Token/Common.hs
haskell/test/Test/Ligo/BaseDAO/Token/Transfer.hs
haskell/test/Test/Ligo/BaseDAO/Token/UpdateOperators.hs
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/defaults.mligo
src/proposal.mligo
src/types.mligo

Problem: Problem: Basically, in a case when a proposal get accepted but it containsoperation that fails, we have the `drop_proposal` entrypoint to remove this proposal.This entrypoint can only be call by the `admin` currently. We no longer want this, andwe want it to be called by anyone. As a result, we need to update to the current `flush`
process, add expiry process, and update `drop_proposal` logic.
Original gist/discussion: https://gist.github.com/gromakovsky/cd03f73f1f5dcc9640def18d0eee642d
Solution: Add `proposal_flush_time_reached` and `proposal_expired_time` to
config, add `guardian` to `storage`, update `flush` and `drop_proposal`
logic.
Detail: https://github.com/tqtezos/baseDAO/issues/87#issuecomment-839716850
Resolves #87
- Tests
[//]: # (Add more …

[#87] Improve handling of failed proposals (2nd Approach)

---

Makefile
docs/building.md
docs/specification.md
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Ligo/BaseDAO/Contract.hs
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/Integrational/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/OffChainViews.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Config.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/defaults.mligo
src/proposal.mligo
src/types.mligo

Problem: We should implement the dynamic update of the quorum threshold
based on the previous participation.
Solution: Introduce the concept of cycle, which is a proposing, voting
period pair. Then track the number of staked tokens in each cycle, and
use it to calculate the new value of quorum-threshold at the very first
propose call in each cycle. Since proposal can be flushed long after the
cycle in which it was proposed, we also store the quorum threshold for
the proposal cycle in the proposals. We use this stored quorum threshold
while evaluating the votes for this proposal.
Another main change in this PR is that we have stopped storing the
denominator for the fractions. This is to simplify the calculations,
mostly in update quorum procedure, and also to round off fractions to
the …

[#207] Dynamic quorum

---

docs/specification.md
haskell/test/Test/Ligo/BaseDAO/Management.hs
src/management.mligo

Problem: In this issue, we are required to modify the behavior of
transfer_ownership entrypoint such that the new admin is set without
having to call accept_ownership call, if the new owner is the address of
the contract itsef.
Soltution: Implement the behavior and update tests and docs.
Resolves #
- Tests
- Haddock

[#215] Accept admin privilege without accept_owenership if new owner if contract itself

---

docs/registry.md
docs/treasury.md
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/common/types.mligo
src/registryDAO.mligo
src/registryDAO/types.mligo
src/treasuryDAO.mligo
src/treasuryDAO/types.mligo

Modifies RegistryDAO proposal types and lambda implementation to allow for transfers and registry updates in the same proposal.
Note: currently based on top of #244
Resolves #242
- Tests
- Haddock

[#242] modify RegistryDAO proposals to transfer with registry updates

---

haskell/src/Ligo/BaseDAO/Types.hs
src/proposal.mligo
src/types.mligo

Problem: when creating a new proposal we store the stage number in
which this was created, however we only need to know in which stage
number this can be voted on.
Solution: modify the proposal type to contain the voting period
stage.
Note: currently based on #245 
Resolves #229
- Tests
- Haddock

[#229] store voting stage number in proposals

---

haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/registryDAO.mligo
src/treasuryDAO.mligo

Problem: Both `treasuryDAO` and `registryDAO` have proposals
that can support xtz transfers.
Both implement `handle_transfer` for `Xtz_transfer_type` in a way
that can fail: empty transactions (of `unit` parameter an `0` amount)
will be rejected by the network.
Solution: `proposal_check` now reject proposal that contains
`Xtz_transfer_type` with 0 mutez, add tests to cover this.
Resolves #257 
- Tests
- Haddock

[#257] Prevent empty transactions in transfer proposals

---

haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Management.hs
src/base_DAO.mligo
src/types.mligo

Problem: We currently have a safety check for most entrypoints to
disallow xtz tokens to be mistakenly sent to the contract and allow
these funds to be stuck there.
We need to reconsider on which entrypoints we should keep this check
and on which we don't need to (see #91).
Solution: Move `accept_ownership` and `transfer_ownership` to
`allowing_xtz` entrypoints.
Resolves #256 
- Tests
- Haddock

[#256] Allow more xtz entrypoints

---

Makefile
ci.nix
docs/building.md
src/defaults.mligo

Problem: Currently, we provide `Makefile` arugments by default and we
handle some storage check silently. This is not really a good idea.
Solution: Remove default values in `Makefile`, and throw error instead.
Add more validate function to storage generation.
Resolves #234 
- Tests
- Haddock

[#234] Throw more and better failure messages on storage creation

---

Makefile
docs/building.md
src/defaults.mligo
src/types.mligo

Problem: there is no option to set the 'max_vote' configuration field
from the Makefile.
Solution: add an option to Makefile for all 3 storage types and a small
check on its value.
Part of the improvements for #233 
- Tests
- Haddock

[#233] allow setting max_votes in the Makefile

---

Makefile

Problem: in the previous PR for this issue (#251) the escaping of
double quotes was removed by mistake from the 'metadata_map' and
'ledger' options in the Makefile storage targets.
Solution: put the escaping back.
Hotfix for #234
- Tests
- Haddock

[#234] put back escaping in metadata_map and ledger Makefile options

---

haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/Management/TransferOwnership.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Flush.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Propose.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Vote.hs

Problem: In our tests, we sometimes send consecutive calls from the same
sender. And in some such places batching can be implemented to make it
faster.
Solution: Find such places, and use batching there. Three places have
been left out because it appear not easy to batch `createSampleProposal`
calls without duplicating some code.
Resolves part of #47 
- Tests
- Haddock

[#47] Implement batch calls in tests where possible

---

docs/specification.md
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Flush.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Propose.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/proposal.mligo

Problem: the conditions for a successful flush are complex and user may
try to optimistically call the entrypoint when unnecessary.
This will create no issue, but will result in gas costs that could be
avoided.
Solution: throw an error when flush is called without any available
proposals.
Resolves #276
- Tests
- Haddock

[#276] throw an error to avoid empty flush calls

---

Makefile
docs/building.md
docs/specification.md
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Config.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Propose.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Vote.hs
src/defaults.mligo
src/proposal.mligo
src/types.mligo

Changes max_votes to max_voters. So the number of voters who has casted a vote on a proposal in counted instead
of the total number of votes. This is done to limit the size of the voters map (for which we will find a sensible default value in #271).
Resolves #277 
- Tests
- Haddock

[#277] Use max voters instead of max votes

---

Makefile
docs/building.md
docs/specification.md
haskell/baseDAO-ligo-meta.cabal
haskell/package.yaml
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/Management.hs
haskell/test/Test/Ligo/BaseDAO/OffChainViews.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Delegate.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Flush.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Propose.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Quorum.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Tokens.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Vote.hs
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/defaults.mligo
src/proposal.mligo
src/types.mligo

Reverts the use of Levels for denoting time intervals. 
Resolves: part of #284
- Tests
- Haddock

[#284] Revert the use of level count to denote time intervals

---

docs/specification.md
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Propose.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Vote.hs
src/proposal.mligo

Problem: It seems that we don't actually check the
'proposal_key_list_sort_by_date' structure for the proposal existence
check. And we should since we only remove proposals from this set during
proposal flush/delete operations.
Solution: In additon to the check in proposals bigmap, check if
'proposal_key_list_sort_by_date' also contains the proposal before
returning success. Add some tests that it works as expected.
Resolves #290 
- Tests
- Haddock

[#290] Check proposal really exist in existence check

---

Makefile
docs/building.md
docs/specification.md
haskell/baseDAO-ligo-meta.cabal
haskell/package.yaml
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Common.hs
haskell/test/Test/Ligo/BaseDAO/Management.hs
haskell/test/Test/Ligo/BaseDAO/OffChainViews.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Delegate.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Flush.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Propose.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Quorum.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Tokens.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Vote.hs
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/TreasuryDAO.hs
src/defaults.mligo
src/proposal.mligo
src/types.mligo

Problem: We had temporarly reverted to using Timestamps for denoting
time intervals. Now we can restore the old behavior.
Solution: Revert commit 9e0c236b9759d4312904dd3af089cd709c20a8d0,
reversing changes made to a21886ed9422ba2e95a95ee23a9aeca95830a58f.
Resolves #284 
- Tests
- Haddock

[#284] Restore use of blocks to denote intervals

---

.github/CONTRIBUTING.md
.xrefcheck.yaml
README.md
haskell/baseDAO-ligo-meta.cabal
haskell/package.yaml
haskell/src/Ligo/BaseDAO/TZIP16Metadata.hs
haskell/test/SMT/Common/Run.hs
scripts/ci/upload-autodoc.sh

Problem: The BaseDAO repo has been moved to tezos-commons organization
so the repo url has been changed.
Solution: We update the references to repo in the source and
documentation.

Update repo location

---

haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/SMT/Common/Gen.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Flush.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Propose.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Quorum.hs

Problem: We have some comment that cautions agaist changing the ordering
of constructors of the Haskell contract parameter. But this is outdated
as the issue causing it have been fixed.
Solution: Change the sort order of constructors and check that tests
pass. Remove the respective comments and TODO.
Resolves #259 
- Tests
- Haddock

[#259] Unsort Haskell constructors

---

Makefile
docs/building.md
docs/error-codes.md
docs/specification.md
haskell/src/Ligo/BaseDAO/ErrorCodes.hs
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/SMT/Common/Gen.hs
haskell/test/SMT/Common/Run.hs
haskell/test/SMT/Model/BaseDAO/Contract.hs
haskell/test/SMT/Model/BaseDAO/Proposal.hs
haskell/test/SMT/Model/BaseDAO/Types.hs
haskell/test/SMT/TreasuryDAO.hs
haskell/test/Test/Ligo/BaseDAO/Common/StorageHelper.hs
haskell/test/Test/Ligo/BaseDAO/ErrorCode.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Config.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Flush.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Propose.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Vote.hs
scripts/generate_error_code.hs
src/base_DAO.mligo
src/defaults.mligo
src/error_codes.mligo
src/proposal.mligo
src/types.mligo
typescript/baseDAO/src/generated/Parameter.ts
typescript/baseDAO/src/generated/Unstake_vote.ts

Problem: The cost of proposals handling increases linearly with the
number of voters due to the fact that we unfreeze voters token on flush.
As a result, we want to to change this behavior to remove the voters
limit and avoid returning tokens on flush.
Solution: Remove returning voter tokens, remove voter limit, add
`Unfreeze_staked` entrypoints, and update the tests.
Resolves #311
- Tests
- Haddock

[#311] Remove voters limit and avoid returning tokens on flush 

---

docs/registry.md
docs/specification.md
docs/treasury.md
docs/trivial.md
src/registryDAO.mligo
src/types.mligo

Problem: the documentation wasn't fully updated to reflect the
behavior of the rejected proposal slash value lambda, the last
time it was changed.
As a result the docs contradict each other in some cases and
don't match the actual behavior.
Solution: fix the various issues in the docs related to this
lambda and its usage.
Fixup for #250 (and probably older issues as well)
- Tests
- Haddock

[#250] fix documentation around rejected proposal slash value

---

docs/error-codes.md
docs/specification.md
haskell/baseDAO-ligo-meta.cabal
haskell/src/Ligo/BaseDAO/ErrorCodes.hs
haskell/src/Ligo/BaseDAO/Types.hs
haskell/test/SMT/Common/Gen.hs
haskell/test/SMT/Model/BaseDAO/Proposal.hs
haskell/test/SMT/Model/BaseDAO/Proposal/Plist.hs
haskell/test/SMT/Model/BaseDAO/Types.hs
haskell/test/Test/Ligo/BaseDAO/Common/StorageHelper.hs
haskell/test/Test/Ligo/BaseDAO/ErrorCode.hs
haskell/test/Test/Ligo/BaseDAO/Plist.hs
haskell/test/Test/Ligo/BaseDAO/Proposal.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Config.hs
haskell/test/Test/Ligo/BaseDAO/Proposal/Propose.hs
scripts/generate_error_code.hs
src/defaults.mligo
src/error_codes.mligo
src/proposal.mligo
src/proposal/plist.mligo
src/types.mligo

Problem: There is currently a limit on the number of concurrent ongoing proposals, due to the fact that proposals need to be sorted (for `flush`) and that this is done using a `set`, which cannot grow indefinitely without causing gas cost problems.
Solution: Remove `proposal_key_list_sort_by_level` and use a doubly linked list instead to store the proposals in order.
Resolves #316
- Tests
- Haddock

[#316] Remove proposal limit and use a linked list for sorting

---

Makefile
haskell/baseDAO-ligo-meta.cabal
haskell/package.yaml
haskell/test/Test/Ligo/BaseDAO/Common/StorageHelper.hs
haskell/test/Test/Ligo/BaseDAO/Plist.hs
haskell/test/Test/Plist/Contract.hs
haskell/test/Test/Plist/Property.hs
haskell/test/Test/Plist/Type.hs
haskell/test/Test/Plist/plist_contract.mligo
src/proposal/plist.mligo
src/types.mligo

Problem: Currently, we only tests plist utility functions one at
a time. It may be helpful to test combinations of them at the same time.
Solution: Add `plist` ligo contract, and add property tests for it
by comparing it with haskell list implementation.
Resolves #319
- Tests
- Haddock

[#319] Add `plist` ligo contract, add property tests for it

---

haskell/test/Test/Ligo/LambdaDAO.hs
src/defaults.mligo

Add a wait period to origination procedure of LambdaDAO tests to ensure that we are past `start-level` before returning from the function. Also fixes a small error in the bound checking of quorum threshold.
Resolves: CI test failures and fixes a small bug in quorum threshold bounds check
- Tests
- Haddock

[#329] Fix lambdadao test timing

---

src/variants/lambdaregistry/implementation.mligo

Problem: In the build process for storage for registry contract, we are not initializing registry key in the contract extra field. This causes registry operations to error out after a fresh deploy.
Solution: Initialize registry key in contract extra duing the build.
Resolves #339
- Tests
- Haddock

[#339] Initialize registry for registry contracts during storage build

---

haskell/baseDAO-ligo-meta.cabal
haskell/test/Test/Ligo/RegistryDAO.hs
haskell/test/Test/Ligo/RegistryDAO/Tests/FlushConfigUpdates.hs
src/variants/lambdaregistry/storage.mligo
src/variants/registry/implementation.mligo
stack.yaml.lock

We were notified of a mistake in the lambda registry's handler for config proposal, which prevents `frozen_extra_value` from being changed.
This makes the required change and adds a regression test, see individual commits messages for details.
None
- Tests
- Haddock

[Chore] Fix config proposal's frozen_extra_value updates in lambda registry

---

typescript/baseDAO/package.json
typescript/baseDAO/yarn.lock

There are some dependabot warnings that we would like to fix. So Update package versions in the yarn.lock file until the warnings go away in the output of `yarn audit`.

[TM-679] Fix dependabot warnings
